### ISSUE TITLE
The number of requests to the spotify API slowly grow over time

### ISSUE THREAD

**Issue by chasingmaxwell** [tim-hellhake/spotify-adapter#19]
I have a [pi-hole](https://pi-hole.net/) set up on my network to block ads/tracking. It has some nifty reporting on all the traffic on my network that helped me spot something troubling. The requests made from my gateway are slowly growing over time:

![Selection_090](https://user-images.githubusercontent.com/3128659/82675736-40946480-9c13-11ea-808d-dd1600de5284.jpg)

That dark blue line is my gateway. When I look at the query log, almost all the requests are to api.spotify.com. I have the add-on configured to poll for playback state every 30 seconds, but it has slowly built up to the point where now it is making ~~24 requests per second~~.

*UPDATE:* Sorry, I was misreading my query log. It's making up to 8 requests per second, but also can sometimes go a second or two without making a request.

**Comment by tim-hellhake** [comment]
Thanks for the detailed report!
If I understood pi-hole correctly it's working as a DNS proxy.
So the number of requests you are seeing might not be actual HTTP requests.
I have no explanation of why the DNS queries would increase linearly over time though.
The only reason I could think of would be crashed zombie add-on processes.
Do you see any errors in the gateway log?
What happens after a gateway start? Is the level back to normal?
I'll dig into the source code of the Spotify client lib in the meantime.
Maybe I can find something which explains this behavior.

**Comment by tim-hellhake** [comment]
Ok I think found something.
The token refresh triggers another poll loop.
This would also explain why it's increasing linearly.

**Comment by chasingmaxwell** [comment]
that aligns with what I'm seeing in my logs (should have posted those to begin with)

```
2020-05-22 06:52:15.440 INFO   : spotify-adapter: Refreshing access token
2020-05-22 06:52:15.551 INFO   : spotify-adapter: Refreshed access token, expires in 3600
2020-05-22 07:37:15.439 INFO   : spotify-adapter: Refreshing access token
2020-05-22 07:37:15.559 INFO   : spotify-adapter: Refreshed access token, expires in 3600
2020-05-22 08:22:15.441 INFO   : spotify-adapter: Refreshing access token
2020-05-22 08:22:15.555 INFO   : spotify-adapter: Refreshed access token, expires in 3600
2020-05-22 09:07:15.450 INFO   : spotify-adapter: Refreshing access token
2020-05-22 09:07:15.560 INFO   : spotify-adapter: Refreshed access token, expires in 3600
2020-05-22 09:37:14.778 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 09:37:14.780 ERROR  : spotify-adapter: { [WebapiError: connect ETIMEDOUT 35.186.224.25:443]
2020-05-22 09:37:14.781 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 09:37:14.782 ERROR  : spotify-adapter:   message: 'connect ETIMEDOUT 35.186.224.25:443',
2020-05-22 09:37:14.783 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 09:43:15.098 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 09:43:15.100 ERROR  : spotify-adapter: { [WebapiError: connect ETIMEDOUT 35.186.224.25:443]
2020-05-22 09:43:15.101 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 09:43:15.102 ERROR  : spotify-adapter:   message: 'connect ETIMEDOUT 35.186.224.25:443',
2020-05-22 09:43:15.103 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 09:46:36.057 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 09:46:36.058 ERROR  : spotify-adapter: { [WebapiError: connect ETIMEDOUT 35.186.224.25:443]
2020-05-22 09:46:36.059 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 09:46:36.059 ERROR  : spotify-adapter:   message: 'connect ETIMEDOUT 35.186.224.25:443',
2020-05-22 09:46:36.060 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 09:46:37.977 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 09:46:37.978 ERROR  : spotify-adapter: { [WebapiError: connect ETIMEDOUT 35.186.224.25:443]
2020-05-22 09:46:37.978 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 09:46:37.979 ERROR  : spotify-adapter:   message: 'connect ETIMEDOUT 35.186.224.25:443',
2020-05-22 09:46:37.980 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 09:52:15.452 INFO   : spotify-adapter: Refreshing access token
2020-05-22 09:52:15.675 INFO   : spotify-adapter: Refreshed access token, expires in 3600
2020-05-22 09:57:50.490 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 09:57:50.493 ERROR  : spotify-adapter: { [WebapiError: getaddrinfo EAI_AGAIN api.spotify.com api.spotify.com:443]
2020-05-22 09:57:50.494 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 09:57:50.495 ERROR  : spotify-adapter:   message: 'getaddrinfo EAI_AGAIN api.spotify.com api.spotify.com:443',
2020-05-22 09:57:50.497 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 10:04:06.949 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 10:04:06.950 ERROR  : spotify-adapter: { [WebapiError: read ECONNRESET]
2020-05-22 10:04:06.951 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 10:04:06.951 ERROR  : spotify-adapter:   message: 'read ECONNRESET',
2020-05-22 10:04:06.952 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 10:04:10.149 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 10:04:10.150 ERROR  : spotify-adapter: { [WebapiError: read ECONNRESET]
2020-05-22 10:04:10.150 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 10:04:10.151 ERROR  : spotify-adapter:   message: 'read ECONNRESET',
2020-05-22 10:04:10.151 ERROR  : spotify-adapter:   statusCode: undefined }
2020-05-22 10:05:33.989 INFO   : spotify-adapter: Unhandled Rejection
2020-05-22 10:05:33.990 ERROR  : spotify-adapter: { [WebapiError: read ECONNRESET]
2020-05-22 10:05:33.990 ERROR  : spotify-adapter:   name: 'WebapiError',
2020-05-22 10:05:33.991 ERROR  : spotify-adapter:   message: 'read ECONNRESET',
2020-05-22 10:05:33.991 ERROR  : spotify-adapter:   statusCode: undefined }
```

**Comment by tim-hellhake** [comment]
I released a new update with the fix.
As soon it's merged to the addon-list repo it will be available in the gateway.
Thank you very much for spotting this erroneous behavior!

**Comment by chasingmaxwell** [comment]
Awesome! Thank you for the quick fix!

**Comment by tim-hellhake** [comment]
Your welcome :)
Let me know if you observe any strange behavior after the update.

**Comment by chasingmaxwell** [comment]
Okay, updated. I'll check my logs later and let you know if I'm still seeing the same linear increase.

**Comment by chasingmaxwell** [comment]
Just checked back and there is no linear increase. I think it's safe to call it!
